name: Bug report
description: Report a problem or unexpected behavior on this code!
title: '[BUG] '
labels: ['type: bug']
assignees: ['']
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the sections below as detailed as possible for us to
        be able to identify, reproduce and fix it.
  - type: checkboxes
    id: before-checks
    attributes:
      label: Some checks before start
      options:
        - label: I searched the issues to avoid duplicate reporting
          required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Describe the actual behavior (i.e. the problem itself)
      placeholder: When I click here this happens...
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: How can we reproduce?
      description: How do you trigger this bug? Please walk us through it step by step.
      placeholder: |
        1.
        2.
        3.
        ...
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: What did you expect to happen when the reproduce steps are followed?
      placeholder: I expected that...
    validations:
      required: true
  - type: textarea
    id: additional-information
    attributes:
      label: Any additional information such as files, screenshots or other information that can help us?
